package com.apptikar.dribbox.presentation.ui.theme

import androidx.compose.ui.graphics.Color
val Blue = Color(0xFF415EB6)
val Yellow = Color(0xFFFFB110)
val Green = Color(0xFF23B0B0)
val Red = Color(0xFFAC4141)
val Orange = Color(0xFFFF842A)
val LightBlue = Color(0xFF567DF4)
val LightBYellow = Color(0xFFFFDE6C)
val LightGreen = Color(0xFF23B0B0)
val LightRed = Color(0xFFF45656)
val Rose = Color(0xFFFF317B)
val BackgroundGray = Color(0xFFE5E5E5)
val OnBackground = Color(0xFF1B1D28)
val ToggleSky =Color(0xFF00BCD4)
val ToggleGray = Color(0xFFFAFAFA)
val CardSky = Color(0xFFEEF7FE)
val CardYellow = Color(0xFFFFFBEC)
val CardRed  = Color(0xFFFEEEEE)
val CardGreen  = Color(0xFFF0FFFF)
val PurpleDark = Color(0xFF22215B)
val TintPurple = Color(0xFF0C0C41)
val PureGreen = Color(0xFF4CE364)
val PureYellow = Color(0xFFFFC700)
val BorderGray = Color(0xFFEEF2FE)
val TintText = Color(0xFF7B7F9E)
val CloseTint = Color(0xFF3A4276)
val SideMenu = Color(0xFFEEF7FE)
val CloudColor = Color(0xFFDDEEFB)
val AvatarBackground = Color(0xFFF1F3F6)
